library(shiny)
library(rhandsontable)
library(leaflet)
# Define UI for application that draws a histogram

source("./helpers/read_list.R")

shinyUI(ui <- navbarPage("DENDROUGHT 2018", id='dendroGlobal', selected='Home',
                         tags$head(
                           tags$link(rel = "stylesheet", type = "text/css", href = "bootstrap.css")
                         ),
                         tabPanel("Home",
                                  includeMarkdown("./pages/Home.Rmd")
                         ),
                         tabPanel("Instructions",
                                  includeMarkdown("./pages/Upload_vignette.Rmd")
                                  ),
                         tabPanel("Upload data",
                         tabsetPanel(id="Submition",
                         tabPanel("Site",
                                  helpText(HTML(
                                    paste("Please enter your Site metadata.",
                                          "<br />",
                                          "<br />",
                                          "'Site Name', 'Longitude' and 'Latitude' are required fields.", 
                                          "<br />", 
                                          "Longitude and Latitude should be provided in decimal degrees with four significant digits (e.g. 13.0713 and 54.1264). After entering coordinates, the map will show the location of your site. Verify that the location is correct.", 
                                          "<br />", 
                                          "<br />",
                                          "After you entered the data, please press Next to verify the metadata and continue to the Dendrometers tab.")
                                  )),
                                  div(style="display:inline-block; width: 25%",
                                      tags$style("#siteID {background-color:#E0FFE0;}"),
                                      textInput("siteID", label=NULL, placeholder="Site Name")),
                                  div(style="display:inline-block; width: 15%", 
                                      tags$style("#long {background-color:#E0FFE0;}"),
                                      textInput("long", label=NULL, placeholder="Longitude")),
                                  div(style="display:inline-block; width: 15%",
                                      tags$style("#lat {background-color:#E0FFE0;}"),
                                      textInput("lat", label=NULL, placeholder="Latitude")),
                                  div(style="display:inline-block; width: 15%",
                                      textInput("elevation",  label=NULL, placeholder="Elevation [m]")),
                                  p(),
                                  div(style="display:inline-block; width: 25%",
                                      selectizeInput("country",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Country", maxItems=1),
                                                     choices = read_list())),
                                  div(style="display:inline-block; width: 15%",
                                      selectizeInput("species_comp",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Species composition", maxItems=1),
                                                     choices = list("Monospecific conifer", 
                                                                    "Mostly mixed conifer",
                                                                    "Mixed forest",
                                                                    "Mostly mixed angiosperm",
                                                                    "Monospecific angiosperm"))),
                                  div(style="display:inline-block; width: 15%",
                                      selectizeInput("slope",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Slope", maxItems=1),
                                                     choices = list("<5%",
                                                                    "5-15%",
                                                                    "15-30%",
                                                                    "30-50%",
                                                                    ">50%"))),
                                  div(style="display:inline-block; width: 15%",
                                      selectizeInput("aspect",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Aspect", maxItems=1),
                                                     choices = list("None",
                                                                    "N",
                                                                    "NE",
                                                                    "E",
                                                                    "SE",
                                                                    "S",
                                                                    "SW",
                                                                    "W",
                                                                    "NW"))),
                                  p(),
                                  div(style="display:inline-block; width: 25%",
                                      selectizeInput("water_holding",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Soil Water Holding Capacity", maxItems=1),
                                                     choices = read_list('lists/water_holding.csv'))),
                                  div(style="display:inline-block; width: 15%",
                                      selectizeInput("soil_depth",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Soil Depth", maxItems=1),
                                                     choices = read_list('lists/soil_depth.csv'))),
                                  div(style="display:inline-block; width: 15%",
                                      selectizeInput("management",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Management", maxItems=1),
                                                     choices = read_list('lists/management.csv'))),
                                  p(),
                                  div(style="display:inline-block; width: 25%",
                                      selectizeInput("other_data",  label=NULL, multiple=TRUE, 
                                                     options = list(placeholder = "Other series availabel upon request [multiple selection]"),
                                                     choices = list("Sapflow", "Leaf phenology", "Cambial phenology", "Stem temperature", 
                                                                    "Leaf water potential", "Stem water potential", "Stem respiration", 
                                                                    "Gas Exchange", "Tree-ring width", "Eddy covariance tower nearby"))),
                                  p(),
                                  div(style="display:inline-block; width: 15%",
                                      actionButton("site_next", "Next")),
                                  uiOutput("Site_check"),
                                  leafletOutput("mymap")

                         ),
                         tabPanel("Dendrometers", value='Dendrometers',
                                  helpText(HTML(
                                    paste("Please, upload your dendrometer data and fill the table that will appear below with the appropriate metadata.",
                                          "<br />",
                                          "<br />",
                                          "Column SensorsID will be automatically filled with your column headers",
                                          "<br />",
                                          "TreeID, Time_Zone, Type, Unit, Measurements_ongoing and Monitored_organ are required fields.",
                                          "<br />",
                                          "<br />",
                                          "After you entered the data, please press Next to verify the metadata and continue to the Trees tab.")
                                  )),
                                  uiOutput('data'),
                                  rHandsontableOutput("dm_meta"),
                                  actionButton("dm_next", "Next"),
                                  uiOutput('Dm_check')
                                  
                         ),
                         tabPanel("Trees",
                                  helpText(HTML(
                                    paste("The Trees table will show with TreeID only if you already filled the Dendrometers TreeID column for all sensors.",
                                          "<br />", 
                                          "<br />",
                                          "Species is required field. Select the species from dropdown menu (preferred) or write it manually into the cell if the your species is missing. In this case the cell will turn red, but the data will still be collected.", 
                                          "<br />",
                                          "<br />",
                                          "After you entered the data, please press Next to verify the metadata and continue to the Environment tab.")
                                    )),
                                  rHandsontableOutput("tree_meta"),
                                  actionButton("tree_next", "Next"),
                                  uiOutput('Tree_check')
                         ),
                         tabPanel("Environment",
                                  helpText(HTML(
                                    paste("Please, upload your environmental data and fill the table that will appear below.",
                                          "<br />",
                                          "<br />",
                                          "SensorID column will be automatically filled with the column headers of your datafile. You should provide at least two environmental variables: Air temperature plus relative humidity and/or precipitation.",
                                          "<br />",
                                          "<br />",
                                          "Parameter, Time_Zone, Site Name and Unit are required fields.",
                                          "<br />",
                                          "<br />",
                                          "For each sensor please select Parameter from dropdown menu (preferred) or write it manually into the cell if the your parameter is missing. In this case the cell will turn red, but the data will still be collected.", 
                                          "<br />",
                                          "<br />",
                                          "In case that some of your data is not monitored on the site, but taken from a non local source, e.g. precipitation from local weather station, please provide the Meteo Station Name.",
                                          "<br />",
                                          "<br />",
                                          "After you entered the data, please press Next to verify the metadata and continue to the Contributors tab.")
                                  )),
                                  uiOutput('clim_data'),
                                  rHandsontableOutput("clim_meta"),
                                  actionButton("clim_next", "Next"),
                                  uiOutput('Clim_check')
                                  
                                  ),
                         tabPanel("Contributors",
                                  helpText(HTML(
                                    paste("Please enter your contact details in the table below.",
                                          "<br />",
                                          "<br />",
                                          "First Name, Last Name, Affiliation and Email are required fields for all authors. Additionally there must be at least one data owner (person owning the data, usually principle investigator), and data manager (person to contact if we need some help with data cleanup or analysis at later stage). They can be the same person, and there can be more than one data owner and manager.",
                                          "<br />",
                                          "<br />",
                                          "In case that are more than one contributor, you can add additional rows to the table by right-clicking and selecting 'Insert row below/above' from the context menu. If you delete all rows by accident context menu also contains Undo statement.",
                                          "<br />",
                                          "<br />",
                                          "After you entered the data, please press Next to verify the metadata and continue to the Submit tab to check and finalize the submission.")
                                  )),
                                  rHandsontableOutput("contributors"),
                                  actionButton("cont_next", "Next"),
                                  uiOutput('Cont_check')
                                  
                         ),
                         tabPanel("Submit",
                                  helpText(HTML(paste('Please wait until report is generated.', 
                                                 '<br />',
                                                 '<br />',
                                                 'If the information below is correct and you are willing to participate in the dendroGlobal initiative, please click Submit button.'))),
                                  uiOutput("Report"),
                                  uiOutput('Submit'),
                                  uiOutput("Submitted"))
                         )),
                         tabPanel("Data policy",
                                  includeMarkdown("./pages/Data_policy.Rmd")),
                         tabPanel("Contact",
                                  includeMarkdown("./pages/Contact.Rmd"))
))
